package ar.com.escuela.exceptions;

public enum EscuelaRestErrorCode {

	OBJECT_NOT_FOUND,
	VALIDATION_ERROR,
	GENERIC_ERROR,
	ACCESS_DENIED,
	INVALID_OR_EXPIRED_TOKEN,
	INVALID_USERNAME_OR_PASSWORD,
	REQUERIDO,
	ALUMNO_INSCRIPTO,
	INVALID_NOTA
}
